services:
  application:
    image: spring-boot-mysql-app  # Ensure this image exists or is built locally
    ports:
      - "8080:8080"
    networks:
      - springboot-db-net
    depends_on:
      - mysqldb
    volumes:
      - /data/springboot-app  # Ensure this directory exists or update it as needed

  mysqldb:
    image: mysql:8
    networks:
      - springboot-db-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=order_service
    volumes:
      - /data/mysql  # Ensure this directory exists or update it as needed

networks:
  springboot-db-net:
