services:
  application:
    build: .  # This will build the image locally from the Dockerfile in the current directory
    ports:
      - "8080:8080"
    networks:
      - springboot-db-net
    depends_on:
      - mysqldb
    volumes:
      - /data/springboot-app

  mysqldb:
    image: mysql:8  # This image will be pulled from Docker Hub
    networks:
      - springboot-db-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=order_service  # Adjust database name if needed
    volumes:
      - /data/mysql

networks:
  springboot-db-net:
