services:
  application:
    build: .  # This tells Docker Compose to build the image locally using the Dockerfile in the current directory
    ports:
      - "8080:8080"
    networks:
      - springboot-db-net
    depends_on:
      - mysqldb
    volumes:
      - /data/springboot-app  # You can adjust this volume if necessary
    
  mysqldb:
    image: mysql:5.7  # This image is pulled from Docker Hub
    networks:
      - springboot-db-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=order_service  # Adjust database name if needed
    volumes:
      - /data/mysql  # You can also adjust this volume if necessary

networks:
  springboot-db-net:
